// the configured options and settings 
// do not edit this file


#ifndef _CONFIG_H_
#define _CONFIG_H_

#define D2TM_PACKAGE  "d2tm"
#define D2TM_VERSION  "0.6.X"
#define D2TM_APP_NAME "Dune II - The Maker"
#define D2TM_OS       "Linux OS"

#endif
