CC=g++
CFLAGS=`sdl-config --cflags` -c -Wall
LDFLAGS=`sdl-config --cflags --libs` -lSDL_image -lSDL_gfx -framework Cocoa
SOURCES=d2tm.cpp map.cpp game.cpp surface.cpp random.cpp keyboard.cpp unit.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=d2tm

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o
	rm d2tm
