CC=g++
CFLAGS=-I/c/MinGW/include/SDL/ -c -Wall
LDFLAGS=-L/c/MinGW/lib -lmingw32 -lSDLmain -lSDL -lSDL_image -lSDL_gfx
SOURCES=d2tm.cpp point.cpp map.cpp game.cpp surface.cpp random.cpp keyboard.cpp mouse.cpp unit.cpp eventfactory.cpp maploader.cpp ini.c INIReader.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=d2tm

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o
	rm d2tm
