CC=g++
CFLAGS=`sdl-config --cflags` -c -Wall
LDFLAGS=`sdl-config --cflags --libs`
SOURCES=d2tm.cpp map.cpp game.cpp CSurface.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=d2tm

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o
	rm d2tm
