CC=g++
CFLAGS=`sdl-config --cflags` -c -Wall -std=c++11
LDFLAGS=`sdl-config --cflags --libs` -lSDL_image -lSDL_gfx
SOURCES=d2tm.cpp point.cpp map.cpp game.cpp surface.cpp random.cpp keyboard.cpp mouse.cpp unit.cpp eventfactory.cpp maploader.cpp ini.c INIReader.cpp unit_move_behavior.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=d2tm

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o
	rm d2tm
