CC=g++
CFLAGS=-I/c/MinGW/include/SDL/ -c -Wall
LDFLAGS=-L/c/MinGW/lib -lmingw32 -lSDLmain -lSDL -lSDL_image 
SOURCES=d2tm.cpp map.cpp game.cpp CSurface.cpp random.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=d2tm

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o
	rm d2tm
