CC=clang++
CFLAGS=-c -Wall -std=c++11 -stdlib=libc++
LDFLAGS=-lsfml-graphics -lsfml-window -lsfml-system  -lc++ -lstdc++
SOURCES=sfml.cpp ini.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=d2tm

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o
	rm d2tm
