; D2TM - DEVELOPER GAME PROFILE.
; 0 MOVESPEED
; 0 TURNSPEED
; 0 BUILDTIME

[HOUSES]
GENERAL_MINIMAPCOLOR = 128,128,128
GENERAL_COLORS_0 = 194,194,218
GENERAL_COLORS_1 = 157,157,186
GENERAL_COLORS_2 = 125,125,153
GENERAL_COLORS_3 = 93,93,121
GENERAL_COLORS_4 = 64,64,89
GENERAL_COLORS_5 = 40,40,60
GENERAL_COLORS_6 = 20,20,40

# 144
HARKONNEN_MINIMAPCOLOR = 255,0,0
HARKONNEN_COLORS_0 = 214,0,0
HARKONNEN_COLORS_1 = 182,0,0
HARKONNEN_COLORS_2 = 153,0,0
HARKONNEN_COLORS_3 = 125,0,0
HARKONNEN_COLORS_4 = 89,0,0
HARKONNEN_COLORS_5 = 60,0,0
HARKONNEN_COLORS_6 = 32,0,0
ATREIDES_MINIMAPCOLOR = 0,0,255
ATREIDES_COLORS_0 = 80,121,214
ATREIDES_COLORS_1 = 52,85,182
ATREIDES_COLORS_2 = 40,60,153
ATREIDES_COLORS_3 = 24,32,125
ATREIDES_COLORS_4 = 8,12,89
ATREIDES_COLORS_5 = 4,4,60
ATREIDES_COLORS_6 = 0,0,32
ORDOS_MINIMAPCOLOR = 0,255,0
ORDOS_COLORS_0 = 76,214,76
ORDOS_COLORS_1 = 56,182,56
ORDOS_COLORS_2 = 36,153,36
ORDOS_COLORS_3 = 24,125,24
ORDOS_COLORS_4 = 12,89,12
ORDOS_COLORS_5 = 4,60,4
ORDOS_COLORS_6 = 0,32,0
MERCENARY_MINIMAPCOLOR = 214,121,16
MERCENARY_COLORS_0 = 214,121,16
MERCENARY_COLORS_1 = 182,97,8
MERCENARY_COLORS_2 = 153,76,4
MERCENARY_COLORS_3 = 121,60,4
MERCENARY_COLORS_4 = 93,40,0
MERCENARY_COLORS_5 = 60,24,0
MERCENARY_COLORS_6 = 32,12,0
SARDAUKAR_MINIMAPCOLOR = 101,12,101
SARDAUKAR_COLORS_0 = 242,105,242
SARDAUKAR_COLORS_1 = 206,72,206
SARDAUKAR_COLORS_2 = 170,48,170
SARDAUKAR_COLORS_3 = 137,24,137
SARDAUKAR_COLORS_4 = 101,12,101
SARDAUKAR_COLORS_5 = 64,0,64
SARDAUKAR_COLORS_6 = 32,0,32

# Fremen is colored as "sand" on the minimap
FREMEN_MINIMAPCOLOR = 194,125,60
FREMEN_COLORS_0 = 214,149,0
FREMEN_COLORS_1 = 182,125,0
FREMEN_COLORS_2 = 153,105,0
FREMEN_COLORS_3 = 125,80,0
FREMEN_COLORS_4 = 89,56,0
FREMEN_COLORS_5 = 60,36,0
FREMEN_COLORS_6 = 32,16,0
CORRINO_MINIMAPCOLOR = 192,192,192
CORRINO_COLORS_0 = 226,182,149
CORRINO_COLORS_1 = 202,161,133
CORRINO_COLORS_2 = 178,141,117
CORRINO_COLORS_3 = 153,121,101
CORRINO_COLORS_4 = 129,101,85
CORRINO_COLORS_5 = 105,80,68
CORRINO_COLORS_6 = 80,60,52




[UNITS]
; ========================================================
; Unit types
; ========================================================
; Editable.
;
; 2 Timers used for units.
; 1 Timer for moving; 100 ticks a second timer. 
; 1 Timer for thinking; 10 ticks a second timer (building speed as well).
;
; For assigning speed to a unit, give amount of ticks needed for moving 1 pixel.
; This means, 0 ticks, is move as fast as possible (fastest). The more ticks
; the slower the movement.
;
; Same rules go for building, turning, move speed, attack (frequency) speed.
;
; The higher the number, the slower the units (the more ticks it needs to
; move one pixel). So MoveSpeed=0 is fastest. Movespeed 10000 will make the
; unit uber slow.
;
; UNIT NAMES MUST BE IN CAPITAL, DO NOT CHANGE THIS OR UNITS WILL NOT BE
; IDENTIFIED WHEN READING THE INI FILE (AN ERROR WILL APPEAR ON LOADING).

; -----------------
; Unit: Sandworm
; -----------------
[UNIT: SANDWORM]
; Unit properties
HitPoints=2500
; Amount of units it can eat, after eating the last unit it will die (to be respawned later)
Appetite=3

; -----------------
; Unit: Ornithopter
; -----------------
[UNIT: ORNITHOPTER]
; Unit properties
HitPoints=40
MoveSpeed=1
TurnSpeed=2
; Attackfrequency is used a bit differently for ornithopters, they have a
; stalled thinking after they have launched their rockets. 
AttackFrequency=2
; Sight will not help ornithopters, they will NOT clear any shroud - unles firing
Sight=0
; Range determines when we are close enough to fire!
Range=9

; Build properties + Sidebar
BuildTime=5
Cost=500

; -----------------
; Unit: Carry-All
; -----------------
[UNIT: CARRYALL]
; Unit properties
HitPoints=50
MoveSpeed=1
TurnSpeed=3
AttackFrequency=0
Sight=0
Range=0

; Build properties + Sidebar
BuildTime=5
Cost=800

; -----------------
; Unit: Harvester
; -----------------
[UNIT: HARVESTER]
; Unit properties
HitPoints=450
MoveSpeed=1
TurnSpeed=1
AttackFrequency=15
Sight=3
Range=3

; Build properties + Sidebar
BuildTime=5
Cost=400

; Harvester specific properties
MaxCredits=700
; 'ticks' to collect...
HarvestSpeed=0
; ... amount of spice
HarvestAmount=10



; -----------------
; Unit: Rocket Launcher
; -----------------
[UNIT: LAUNCHER]
; Unit properties
HitPoints=130
MoveSpeed=1
TurnSpeed=1
AttackFrequency=25
Sight=9
Range=8

; Build properties + Sidebar
BuildTime=5
Cost=400

; -----------------
; Unit: Deviator
; -----------------
[UNIT: DEVIATOR]
HitPoints=70
MoveSpeed=1
TurnSpeed=1
AttackFrequency=35
Sight=8
Range=8

; Build properties + Sidebar
BuildTime=5
Cost=700

; -----------------
; Unit: Devastator
; -----------------
[UNIT: DEVASTATOR]
; Unit properties
HitPoints=800
MoveSpeed=1
TurnSpeed=1
AttackFrequency=42
Sight=6
Range=5

; Build properties + Sidebar
BuildTime=5
Cost=900

; -----------------
; Unit: Siege Tank
; -----------------
[UNIT: SIEGETANK]
; Unit properties
HitPoints=400
MoveSpeed=1
TurnSpeed=1
AttackFrequency=17
Sight=6
Range=5

; Build properties + Sidebar
BuildTime=5
Cost=600

; -----------------
; Unit: Tank
; -----------------
[UNIT: COMBATTANK]
; Unit properties
HitPoints=175
MoveSpeed=1
TurnSpeed=1
AttackFrequency=8
Sight=5
Range=4

; Build properties + Sidebar
BuildTime=5
Cost=300

; -----------------
; Unit: Sonic Tank
; -----------------
[UNIT: SONICTANK]
; Unit properties
HitPoints=220
MoveSpeed=1
TurnSpeed=1
AttackFrequency=18
Sight=7
Range=7

; Build properties + Sidebar
BuildTime=5
Cost=600

; -----------------
; Unit: Quad
; -----------------
[UNIT: QUAD]
HitPoints=130
MoveSpeed=1
TurnSpeed=1
AttackFrequency=12
Sight=4
Range=3
BuildTime=5
Cost=200

; -----------------
; Unit: Trike
; -----------------
[UNIT: TRIKE]
HitPoints=100
MoveSpeed=1
TurnSpeed=1
AttackFrequency=8
Sight=4
Range=3
Cost=150
BuildTime=5


; -----------------
; Unit: Raider Trike
; -----------------
[UNIT: RAIDER]
; Unit properties
HitPoints=40
MoveSpeed=1
TurnSpeed=1
AttackFrequency=5
Sight=5
Range=2

; Build properties + Sidebar
BuildTime=5
Cost=125


; INFANTRY / TROOPERS / ETC

; -----------------
; Unit: Soldier
; -----------------
[UNIT: SOLDIER]
; Unit properties
HitPoints=40
MoveSpeed=1
TurnSpeed=1
AttackFrequency=6
Sight=2
Range=2

; Build properties + Sidebar
BuildTime=5
Cost=60



; -----------------
; Unit: Infantry
; -----------------
[UNIT: INFANTRY]
; Unit properties
HitPoints=120
MoveSpeed=1
TurnSpeed=1
AttackFrequency=6
Sight=3
Range=2

; Build properties + Sidebar
BuildTime=5
Cost=100

; -----------------
; Unit: Trooper
; -----------------
[UNIT: TROOPER]
; Unit properties
HitPoints=60
MoveSpeed=1
TurnSpeed=1
AttackFrequency=15
Sight=3
Range=5

; Build properties + Sidebar
BuildTime=5
Cost=80

; -----------------
; Unit: Troopers
; -----------------
[UNIT: TROOPERS]
; Unit properties
HitPoints=180
MoveSpeed=1
TurnSpeed=1
AttackFrequency=15
Sight=4
Range=5

; Build properties + Sidebar
BuildTime=38
Cost=175
; -----------------
; Unit: Mobile Construction Vehicle
; -----------------
[UNIT: MCV]
HitPoints=200
MoveSpeed=1
TurnSpeed=1
AttackFrequency=0
Sight=5
Range=0
Cost=999
BuildTime=5

; -------------------------------------
; PALACE SPECIFIC UNITS
; -------------------------------------
; NOTE: "Missile" = Dead hand. Is not a real unit

; -----------------
; Unit: FREMEN TROOPERS (Atreides palace stuff)
; -----------------
[UNIT: FREMEN]
; Unit properties
HitPoints=150
MoveSpeed=1
TurnSpeed=1
AttackFrequency=14
Sight=6
Range=6

; Build properties + Sidebar
; Buildtime = 1000, equals saboteur
BuildTime=5
; costs nothing
Cost=0

Unit: Triple fremen (Atreides)
; this unit is used in the sidebar! (so the cost and buildtime of this one are
; used!)
; -----------------
[UNIT: THREEFREMEN]
; Unit properties
HitPoints=450
MoveSpeed=4
TurnSpeed=2
AttackFrequency=14
Sight=6
Range=6

; Build properties + Sidebar
; Buildtime = 1000, equals saboteur
BuildTime=5
; costs nothing
Cost=0

; -----------------

; -----------------
; MISSILE - HARKONNEN
; -----------------
[UNIT: MISSILE]
; Buildtime = 1000, equals saboteur
; Missile is a bit longer because its strong
BuildTime=5
; costs nothing
Cost=0

; -----------------
; Unit: SABOTEUR (ordos specific stuff)
; -----------------
[UNIT: SABOTEUR]
; Unit properties
HitPoints=150
MoveSpeed=1
TurnSpeed=1
AttackFrequency=0
Sight=3
Range=2
  
; Build properties + Sidebar
; Buildtime = 1000, equals saboteur
BuildTime=5
; costs nothing
Cost=0

; ========================================================
; Structure types
; ========================================================
; Note: The settings here are on default (House Atreides) skill
;
; Cost=Cost 
; HitPoints=hp
; FixPoints= how much hp per tick will be 'fixed'
; BuildTime=ticks to build this
; PowerDrain=how much power this drains
; PowerGive=how much power this gives
[STRUCTURES]

; ---------------------
; Structure: Palace
; ---------------------
[STRUCTURE: PALACE]
Cost=999
HitPoints=2000
FixPoints=1
BuildTime=5
PowerDrain=80
PowerGive=0
UponDestructionSpawnUnitAmountMin=3
UponDestructionSpawnUnitAmountMax=5

; ---------------------
; Structure: Windtrap
; ---------------------
[STRUCTURE: WINDTRAP]
Cost=300
HitPoints=500
FixPoints=3
BuildTime=5
PowerDrain=0
PowerGive=100
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=2

; ---------------------
; Structure: Heavy Factory
; ---------------------
[STRUCTURE: HEAVYFACTORY]
Cost=600
HitPoints=700
FixPoints=2
BuildTime=5
PowerDrain=30
PowerGive=0
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=3

; ---------------------
; Structure: Light Factory
; ---------------------
[STRUCTURE: LIGHTFACTORY]
Cost=400
HitPoints=350
FixPoints=3
BuildTime=5
PowerDrain=20
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=2

; ---------------------
; Structure: Construction Yard
; ---------------------
[STRUCTURE: CONSTYARD]
; the Cost of the ConstYard is used to determine upgrade price (=50% of cost - for now)
Cost=400
HitPoints=1000
FixPoints=3
BuildTime=5
PowerDrain=0
PowerGive=1
HasConcrete=False
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=2

; ---------------------
; Structure: Silo
; ---------------------
[STRUCTURE: SILO]
Cost=150
HitPoints=250
FixPoints=5
BuildTime=5
PowerDrain=5
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=2

; ---------------------
; Structure: High-Tech
; ---------------------
[STRUCTURE: HIGHTECH]
Cost=600
HitPoints=600
FixPoints=2
BuildTime=5
PowerDrain=35
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=3

; ---------------------
; Structure: House of IX
; ---------------------
[STRUCTURE: IX]
Cost=700
HitPoints=700
FixPoints=2
BuildTime=5
PowerDrain=60
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=2

; ---------------------
; Structure: Repair Facility
; ---------------------
[STRUCTURE: REPAIR]
Cost=700
HitPoints=250
FixPoints=5
BuildTime=5
PowerDrain=20
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=3

; ---------------------
; Structure: Radar
; ---------------------
[STRUCTURE: RADAR]
Cost=400
HitPoints=900
FixPoints=3
BuildTime=5
PowerDrain=30
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=2

; ---------------------
; Structure: Spice Refinery
; ---------------------
[STRUCTURE: REFINERY]
Cost=400
HitPoints=800
FixPoints=3
BuildTime=5
PowerDrain=30
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=3

; ---------------------
; Structure: WOR
; ---------------------
[STRUCTURE: WOR]
Cost=400
HitPoints=500
FixPoints=3
BuildTime=5
PowerDrain=20
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=2

; ---------------------
; Structure: Barracks
; ---------------------
[STRUCTURE: BARRACKS]
Cost=400
HitPoints=300
FixPoints=4
BuildTime=5
PowerDrain=10
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=1
UponDestructionSpawnUnitAmountMax=2

; ---------------------
; Structure: Starport
; ---------------------
[STRUCTURE: STARPORT]
Cost=500
HitPoints=800
FixPoints=3
BuildTime=5
PowerDrain=50
PowerGive=0
UponDestructionSpawnUnitType=SOLDIER
UponDestructionSpawnUnitAmountMin=2
UponDestructionSpawnUnitAmountMax=4

; ---------------------
; Structure: Gun Turret
; ---------------------
[STRUCTURE: TURRET]
Cost=150
HitPoints=400
FixPoints=2
BuildTime=5
PowerDrain=10
PowerGive=0
Sight=7
Range=7
FireRate=275

; ---------------------
; Structure: Rocket Turret
; ---------------------
[STRUCTURE: ROCKETTURRET]
Cost=250
HitPoints=800
FixPoints=3
BuildTime=5
PowerDrain=20
PowerGive=0
Sight=10
Range=7
FireRate=350


; ==================================================
; the following 'structure types' are not 'really'
; structures. However, you can adjust the price and
; buildtime of those:
; ==================================================

[STRUCTURE: SLAB]
Cost=5
BuildTime=5
PowerDrain=0
PowerGive=0

[STRUCTURE: 4SLAB]
Cost=20
BuildTime=5
PowerDrain=0
PowerGive=0

; WALL has hitpoints (FixPoints will not work here)
[STRUCTURE: WALL]
Cost=50
BuildTime=5
HitPoints=200
PowerDrain=0
PowerGive=0

; End of file
