#!/bin/sh

help () {
    cat <<EOF

  Usage: fix.sh platform

  Where platform is one of: unix

EOF
    exit
}

if [ -z "$1" ]; then
    help
fi

case "$1" in
    unix) 
	MAKE_COMPILER=gcc
	MAKEFILE=makefile.unx
	;;
    *)
	help
	;;
esac

echo Configuring FBlend for $MAKE_COMPILER...

echo \# generated by fix.sh > makefile
echo include make/$MAKEFILE >> makefile

echo Done\! Now run make to start the compilation.

