#pragma once

enum class eKeyAction {
    // Global
    SCREENSHOT,
    TOGGLE_MUSIC,
    MUSIC_VOLUME_DOWN,
    MUSIC_VOLUME_UP,
    GAME_SPEED_UP,
    GAME_SPEED_DOWN,
    TOGGLE_FULLSCREEN,
    TOGGLE_CHEAT,
    // Map scrolling
    SCROLL_LEFT,
    SCROLL_RIGHT,
    SCROLL_UP,
    SCROLL_DOWN,
    // Gameplay
    CENTER_ON_HOME,
    CENTER_ON_STRUCTURE,
    ZOOM_RESET,
    TOGGLE_FPS,
    TOGGLE_TIME_DISPLAY,
    OPEN_MENU,
    DEPLOY_UNIT,
    SET_PRIMARY,
    // Unit commands
    ATTACK_MODE,
    ADD_TO_SELECTION,
    REPAIR_UNIT,
    RETURN_TO_BASE,
    SEND_TO_REFINERY,
    SELECT_SAME_TYPE_ON_SCREEN,
    // Groups
    GROUP_1,
    GROUP_2,
    GROUP_3,
    GROUP_4,
    GROUP_5,
    // Editor
    EDITOR_SAVE,
    EDITOR_ZOOM_IN,
    EDITOR_ZOOM_OUT,
    // UI / menus
    MENU_BACK,
    MENU_CONFIRM,
    MENU_CANCEL,
    // Debug
    DEBUG_WIN,
    DEBUG_LOSE,
    DEBUG_GIVE_CREDITS,
    DEBUG_DESTROY_AT_CURSOR,
    DEBUG_REVEAL_MAP,
    DEBUG_DAMAGE_AT_CURSOR,
    DEBUG_KILL_CARRYALLS,
    DEBUG_SPAWN_ORNITHOPTER,
    DEBUG_CLEAR_SHROUD_AT_CURSOR,
    DEBUG_SWITCH_PLAYER_0,
    DEBUG_SWITCH_PLAYER_1,
    DEBUG_SWITCH_PLAYER_2,
    DEBUG_SWITCH_PLAYER_3,
};
