name: CI

# Workflow file for windows
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Cache MinGW modules
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey\mingw\8.1.0\
          #path: C:\ProgramData\chocolatey\lib\mingw\

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
         platform: x86 # D2TM is built within a MinGW32 bit environment

      - name: Running cmake (windows)
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"

      - name: Build
        run: |
          cd build
          cmake --build . --target all -- -j 6