# Trigger the workflow on milestone events
on:
  milestone:
    types: [closed]
name: Milestone Closure v2
jobs:
  create-release-notes-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: github_release
        uses: okcredit/changelog-creator-action@v1.0.0
        with:
          configuration: ".github/workflows/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create temp dir
        run: mkdir temp_release_notes

      - name: Print change log
        run: echo "${{ steps.github_release.outputs.changelog }}" >> temp_release_notes/release.md

      - name: Upload Release Notes to Wiki
        uses: docker://decathlon/wiki-page-creator-action:2.0.2
        env:
          GH_PAT: ${{ secrets.GH_PAT_D2TM }}
          ACTION_MAIL: stefan@fundynamic.com
          ACTION_NAME: stefanhendriks
          OWNER: stefanhendriks
          REPO_NAME: Dune-II---The-Maker
          MD_FOLDER: temp_release_notes