name: "Create Release & Notes"
on:
  workflow_dispatch:
    inputs:
      from-tag-name:
        description: 'Existing previous git tag to use. Ie the previous release.'
        required: true
      tag-name:
        description: 'Existing new tag to use for drafting release notes.'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: "3.14"

      - name: Generate Release Notes
        id: notes
        uses: AbsaOSS/generate-release-notes@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-name: ${{ github.event.inputs.tag-name }}
          from-tag-name: ${{ github.event.inputs.from-tag-name }}
          chapters: |
            - {"title": "🚀 Features", "labels": "feature, improvement"}
            - {"title": "🎲 Gameplay", "labels": "balancing"}
            - {"title": "🧩️ Dune 2 features", "label": "missing-dune2-piece"}
            - {"title": "🧪 Experimental", "label": "experimental"}
            - {"title": "🐛 Fixes", "labels": "bug"}
            - {"title": "⚙️ Technical", "labels": "refactoring, technical"}

      - name: Create temp dir
        run: |
          mkdir -p temp_release_notes
          printf "%s" "${{ steps.notes.outputs.release-notes }}" >> temp_release_notes/${{ github.event.inputs.tag-name }}.md

      - name: Upload Release Notes to Wiki
        uses: docker://decathlon/wiki-page-creator-action:2.0.2
        env:
          GH_PAT: ${{ secrets.GH_PAT_D2TM }}
          ACTION_MAIL: stefan@fundynamic.com
          ACTION_NAME: stefanhendriks
          OWNER: stefanhendriks
          REPO_NAME: Dune-II---The-Maker
          MD_FOLDER: temp_release_notes