#----------------------------------#
#--- Source file list -------------#

C_SOURCE = cadd.c mem_test.c csub.c ctrans.c radd.c rtrans.c 2xstretch.c fade.c

ASM_SOURCE = cadd16.s   cadd15.s   cadd32.s   \
             csub16.s   csub15.s   csub32.s   \
             trans16.s  trans15.s  trans32.s  \
             radd16.s   radd15.s   radd32.s   \
             rtrans16.s rtrans15.s rtrans32.s \
             2xstretch.s                      \
             fade16.s   fade15.s   fade32.s   \
             mem_test.s
             

ASM_DEPEND = asmdefs.inc fblend.inc blit.inc rect.inc stretch.inc cadd.inc trans.inc fade.inc

EXAMP_SOURCE = exadd.c exsub.c extrans.c exradd.c exrtrans.c exstretch.c exfade.c


default: all
all: examples lib
	@echo -
	@echo Success!
	@echo Now run 'make install' to install FBlend.


#----------------------------------#
#-- Set up names and dependencies -#

SRC_DIR = src
LIB_DIR = lib/$(COMPILER)
EXAMPLE_DIR = examples
MAIN_INCLUDE_PATH = include/fblend.h
INCLUDE_DIR = . src include


ifdef DEBUGMODE
  OBJ_DIR = obj/$(COMPILER)/debug
  LIB_NAME = fblendd
  LINK_LIB = alleg
else

ifdef PROFILEMODE
  OBJ_DIR = obj/$(COMPILER)/profile
  LIB_NAME = fblendp
  LINK_LIB = alleg
else

  OBJ_DIR = obj/$(COMPILER)/release
  LIB_NAME = fblend
  LINK_LIB = alleg
endif
endif
